#!/bin/sh

set -o nounset
set -o errexit


#autorandr --change --default default
#exit 0

DMENU="rofi -dmenu -l 4"

mkdir -p "$HOME/.config/autorandr"

choices=$(echo "auto"; cd $HOME/.config/autorandr; ls -1 | grep -v default | sort; echo "arandr")

chosen=$(echo -e "$choices" | $DMENU -p "Display layout")

case "$chosen" in
  auto) autorandr --change --default default ;;
  arandr) arandr ;;
  *) autorandr --change $chosen ;;
esac

sleep 2
dunstify "Changed screen layout to $(autorandr --current)"
